services:
  - type: web
    name: shl-assessment-recommender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: GEMINI_TEMPERATURE
        value: "0.2"
      - key: GEMINI_MAX_OUTPUT_TOKENS
        value: "512"
      - key: CATALOG_URL
        value: https://tcp-us-prod-rnd.shl.com/voiceRater/shl-ai-hiring/shl_product_catalog.json
      - key: CATALOG_PATH
        value: app/data/shl_product_catalog.json
      - key: FAISS_INDEX_PATH
        value: app/data/shl_catalog.faiss
      - key: METADATA_PATH
        value: app/data/shl_catalog_metadata.json
      - key: MODEL_CACHE_DIR
        value: app/data/model_cache
